name: Warp-Point-Plugin
main: WarpPointPlugin
api-version: 1.16
version: 1.0
commands:
  setwarp:
    usage: /setwarp

  gowarp:
    usage: /gowarp

    description: Teleportiert dich zu dem vorherig gesetzten Block-Koordinaten.